# Generated by Django 6.0.5 on 2026-06-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insured', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('insured_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contracts', to='insured.insuredperson')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='insured.insurancetype')),
            ],
        ),
    ]
