# Generated by Django 6.0.5 on 2026-06-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insured', '0002_insurancetype_insurancecontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuredperson',
            name='insurance_type',
        ),
    ]
